### ISSUE TITLE
Images not being generated

### ISSUE THREAD

**Issue by andylarkum** [statamic/ssg#103]
This is a recent issue (like, has only been a problem in the last couple of weeks).

Running `php please ssg:generate` isn't generating the image files for newly added content. Anything older than a couple of weeks ago is working fine, but anything added in the last couple of weeks fails to create.

For clarity, the local "live" version of the site works fine, the static version is missing the new images.

No idea where to start debugging this - any pointers/things I can try?

**Comment by joshuablum** [comment]
Hey @andylarkum,

What's the output of `php please support:details`?
And what do your config files look like? Specifically `config/statamic/assets.php` & `config/statamic/ssg.php`

**Comment by andylarkum** [comment]
Hi @joshuablum 

Thanks for getting back to me here. Results:

`php please support:details`
Statamic 3.3.16 Solo
Laravel 8.83.17
PHP 8.0.19
cnj/seotamic 2.0.6
octoper/statamic-html-minify 0.0.5
pecotamic/sitemap 1.4.0
rias/statamic-redirect 2.3.6
statamic/ssg 1.0.1

`confic/statamic/assets.php` stripped of comments:
`return [

    'image_manipulation' => [
        'route' => 'img',
        'secure' => true,
        'driver' => 'gd',
        'cache' => false,
        'cache_path' => public_path('img'),
        'presets' => [
            'xs-webp' => ['w' => 320, 'h' => 10000, 'q' => 85, 'fit' => 'contain', 'fm' => 'webp'],
            'sm-webp' => ['w' => 480, 'h' => 10000, 'q' => 85, 'fit' => 'contain', 'fm' => 'webp'],
            'md-webp' => ['w' => 768, 'h' => 10000, 'q' => 85, 'fit' => 'contain', 'fm' => 'webp'],
            'lg-webp' => ['w' => 1280, 'h' => 10000, 'q' => 85, 'fit' => 'contain', 'fm' => 'webp'],
            'xl-webp' => ['w' => 1440, 'h' => 10000, 'q' => 95, 'fit' => 'contain', 'fm' => 'webp'],
            '2xl-webp' => ['w' => 1680, 'h' => 10000, 'q' => 95, 'fit' => 'contain', 'fm' => 'webp'],
            'xs' => ['w' => 320, 'h' => 10000, 'q' => 85, 'fit' => 'contain'],
            'sm' => ['w' => 480, 'h' => 10000, 'q' => 85, 'fit' => 'contain'],
            'md' => ['w' => 768, 'h' => 10000, 'q' => 85, 'fit' => 'contain'],
            'lg' => ['w' => 1280, 'h' => 10000, 'q' => 85, 'fit' => 'contain'],
            'xl' => ['w' => 1440, 'h' => 10000, 'q' => 95, 'fit' => 'contain'],
            '2xl' => ['w' => 1680, 'h' => 10000, 'q' => 95, 'fit' => 'contain'],
        ],
    ],
    'auto_crop' => true,
    'thumbnails' => [
        'max_width' => 10000,
        'max_height' => 10000,
    ],
    'google_docs_viewer' => false,
    'cache_meta' => true,

];`

...and `config/statamic/ssg.php`:
`return [
    'base_url' => config('app.url'),
    'destination' => storage_path('app/static'),
    'copy' => [
        public_path('css') => 'css',
        public_path('js') => 'js',
        public_path('assets') => 'assets',
        public_path('fonts') => 'fonts',
    ],

    'symlinks' => [
        // public_path('css') => 'css',
        // public_path('js') => 'js',
    ],
    'urls' => [
        '/posts',
        'sitemap.xml',
        'robots.txt'
    ],
    'exclude' => [
        //
    ],
    'glide' => [
        'directory' => 'img',
    ],
    'failures' => false, // 'errors' or 'warnings'
];`

**Comment by joshuablum** [comment]
Thanks for providing those details! Config looks fine to me.

What's interesting: Someone else that ran into the issue was also on Laravel 8 and PHP 8.0. If it's not too much work, could you try upgrading to Laravel 9 and PHP 8.1?

**Comment by andylarkum** [comment]
OKey doke

I've updated to Laravel 9 and PHP 8.1, regenerated and re-synched to AWS S3.
Now just need for cloudfront to update :)

I'll update soon...

A.

**Comment by andylarkum** [comment]
Nope

Still no images. 

Stumped

**Comment by joshuablum** [comment]
Thanks for the update and for upgrading to Laravel 9 and PHP 8.1!

Are you running the plain `php please ssg:generate` command or are you also passing the `--workers` argument to it? If you're using workers, could you try to run it without them.

**Comment by andylarkum** [comment]
Yup, just generate, no workers

**Comment by jasonvarga** [comment]
Where are you running the `ssg:generate` command? On production? Locally?

If you run `php artisan cache:clear` before `ssg:generate`, do the new images appear?

**Comment by andylarkum** [comment]
Hi @jasonvarga 
Running `ssg:generate` on local

I discovered that I have to run `php please cache:clear` before AND after `ssg:generate`, otherwise

1. generate fails; and
2. the local site errors afterwards

...but, perhaps I'll get a different result with `php artisan cache:clear`?

**Comment by globalexport** [comment]
Hi @andylarkum,

Are the images physically missing in the generated folder, or do you maybe experience the same behaviour in HTML I found with using the spatie responsive image plugin after the update: https://github.com/spatie/statamic-responsive-images/issues/146
