### ISSUE TITLE
Generating explicit URLs from routes requires an APP_KEY

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ssg#12]
If you specify URLs in the `urls` setting that use routes, they won't generate unless you have an `APP_KEY`. This isn't a problem locally or on a traditional staging server, but the previous behavior and current Netlify docs don't require setting an APP_KEY, so following them exactly will end up with 404s on these URLs.

I'm assuming that it's because this url is using a `Route::statamic()`, which requires Statamic/Laravel to run, which requires an APP_KEY and that's just the way it is, but wanted to confirm.

![image](https://user-images.githubusercontent.com/44739/73594387-1ee46580-44dc-11ea-8b38-b858d037a81d.png)

**Comment by jasonvarga** [comment]
Yeah, sorta just the way it is with how these routes are generated. They're actually booting the whole app/request.

We briefly discussed internally that maybe we could automatically handle any routes defined with `Route::statamic()`. I could see those working without needing real HTTP requests.

**Comment by jasonvarga** [comment]
I don't think we can get around this.

It's just a fluke that you don't see an error on content urls. If something within there needs an instance of the encrypter, you'd also see the error.

Laravel/Statamic sites need an app key.
