### ISSUE TITLE
Torchlight not working with Statamic SSG

### ISSUE THREAD

**Issue by mbootsman** [statamic/ssg#150]
I am using / trying to use Torchlight with Statamic and used the docs to install it.
All works local in default Statamic install. But it fails when I deploy to Netlify, and also fails when I generate the the static files with SSG locally. The code blocks are not rendered but I see code blocks with `__torchlight-block-[9a3f0b40-2ec4-4169-9788-22e812836e47]__` messages.

Help is appreciated. The website repo is here: https://github.com/mbootsman/marcelbootsman-statamic

**Comment by joshuablum** [comment]
Hey @mbootsman,

Using Torchlight together with the `ssg` package requires a few extra steps. They are described [here](https://github.com/torchlight-api/torchlight-laravel/issues/22).

Hope that helps :)

Just reopen if you're still having issues.
