### ISSUE TITLE
Generation fails with "Unresolvable dependency resolving" error

### ISSUE THREAD

**Issue by anthonynelzin** [statamic/ssg#153]
Hi, 

since upgrading to Statamic 4.28.0 and SSG 2.2.0 with PHP 8.2.11, our static site generation pipeline has been broken. Using the `php please ssg:generate` command results in the following error:

```
In Container.php line 1118:
Unresolvable dependency resolving [Parameter #1 [ <required> $customStubPath ]] in class Illuminate\Database\Migrations\MigrationCreator
```

Removing the offending class in the Laravel framework allows for the generation, but isn’t a viable "solution".

**Comment by jasonvarga** [comment]
Can you show your `config/app.php` file?

I suspect maybe you don't have the the providers set up correctly. Maybe something incorrect with the upgrade?

You should see something like this:

https://github.com/statamic/statamic/blob/f811c5b3e79a05882020e9e2cc266f746ca0793e/config/app.php#L158-L171

**Comment by anthonynelzin** [comment]
Hi Jason,

sorry for the delay. I don’t think we’ve touched this file since we first set the site up, but here you go:

[app.txt](https://github.com/statamic/ssg/files/12929399/app.txt)

**Comment by jasonvarga** [comment]
Looks fine. Can you try another `composer update`?

**Comment by anthonynelzin** [comment]
Good call. I nuked my `composer.json` file that dates back from Statamic 3 to adhere to the current one… and everything worked on the first try. It lacked some Laravel packages (Sanctum, Pint, Sail). Thank you very much!

**Comment by jasonvarga** [comment]
Beautiful!
