### ISSUE TITLE
Does SSG require that base_url be at the root of a server?

### ISSUE THREAD

**Issue by efc** [statamic/ssg#179]
I would like to "base" my static site in a folder on the server I am targeting. So I have configured `ssg.php` so that `'base_url' => 'https://mysite.com/folder'`. However, all the URLs generated for the site when exporting the static site are still rooted at `/` (such as `/assets` instead of `/folder/assets`).

Does the SSG assume that `base_url` is at the root of a server? Or is there some way that Statamic and SSG can be configures so as to be agnostic to whether the site is running deeper in the folder hierarchy?

**Comment by duncanmcclean** [comment]
I *think* the `base_url` is correct.

> However, all the URLs generated for the site when exporting the static site are still rooted at / (such as /assets instead of /folder/assets).

How are you linking to assets?

**Comment by efc** [comment]
I just built my own "after" extension at (see this [code for use with alt-redirect](https://github.com/alt-design/Alt-Redirect-Addon/issues/15 ) that builds static HTML redirects) and found that I could easily incorporate the `base_url` config into the links I was building. I'm just not sure why SSG is not doing this when I build links in Antlers. Is there an Antlers tag I should be using other than those I mentioned above?

**Comment by efc** [comment]
Still have no idea why the various Antlers variables and modifiers mentioned above are not sensitive to being run in the SSG context, but I really want to push my site out. I realized that I could take a heavy hand and force a "solution" by rewriting URLs after the SSG finished its work. The code below was largely written by ChatGPT (I know...), but I am shocked by how well this approach is working. Basically, it walks through the all the HTML files that SSG has pushed out and rewrites all the absolute links with the base prefix.

```php
        SSG::after(function () {
            $dest = config('statamic.ssg.destination');
            $base = rtrim(config('statamic.ssg.base_url'), '/'); // remove trailing slash

            // Add basees to all absolute URLs if base_url was not '/'

            if ($base) {
                $processed_count = 0;

                echo "Rewriting absolute URLs to add $base prefix\n";

                $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($dest));

                $modifyUrl = function ($url) use ($base) {
                    // there could probably be a more sophisticated check for absolute URLs
                    if (str_starts_with($url, '/') && !str_starts_with($url, '//')) {
                        // make sure the URL does not already start with base
                        if (strpos($url, $base) !== 0) {
                            return $base . $url;
                        }
                    }
                    return $url;
                };

                foreach ($iterator as $fileInfo) {
                    if ($fileInfo->isFile() && $fileInfo->getExtension() === 'html') {
                        $filePath = $fileInfo->getPathname();
                        $htmlContent = file_get_contents($filePath);

                        $dom = new \DOMDocument();
                        // suppress errors due to malformed HTML
                        libxml_use_internal_errors(true);
                        $dom->loadHTML($htmlContent);
                        libxml_clear_errors();

                        $links = $dom->getElementsByTagName('a');
                        $images = $dom->getElementsByTagName('img');

                        foreach ($links as $link) {
                            /** @disregard P1013 Undefined method */
                            $href = $link->getAttribute('href');
                            $newHref = $modifyUrl($href);
                            /** @disregard P1013 Undefined method */
                            $link->setAttribute('href', $newHref);
                        }

                        foreach ($images as $image) {
                            /** @disregard P1013 Undefined method */
                            $src = $image->getAttribute('src');
                            $newSrc = $modifyUrl($src);
                            /** @disregard P1013 Undefined method */
                            $image->setAttribute('src', $newSrc);
                        }

                        $modifiedHtml = $dom->saveHTML();
                        file_put_contents($filePath, $modifiedHtml);

                        $processed_count++;
                    }
                }

                echo "Processed $processed_count HTML files\n";
            }
        });
```
On my M2 Mac this rewrites over 1000 files in less than one second.

**Comment by efc** [comment]
After some further review, all this may be just my newbie misunderstanding of how Statamic sites work. I just realized that on my Statamic site config (CP > Settings > Site > URL) I can specify that the site should be served from the site URL of `/folder`. If I do this, then the SSG configuration I described at the top does just fine. So I don't actually think there is an issue here, just a misunderstanding on my part.

**Comment by efc** [comment]
No change needed.

**Comment by efc** [comment]
After some further review, all this may be just my newbie misunderstanding of how Statamic sites work. I just realized that on my Statamic site config (CP > Settings > Site > URL) I can specify that the site should be served from the site URL of `/folder`. If I do this, then the SSG configuration I described at the top does just fine. So I don't actually think there is an issue here, just a misunderstanding on my part.

**Comment by duncanmcclean** [comment]
Apologies for not getting back to you (I don't know much about the SSG myself 🙈). 

> Some examples...
> 
>     * `<a href="{{ site.url }}">` renders as `<a href="/">`
> 
>     * `<a href="{{ mount_url handle="wiki" }}">` renders as `<a href="/wiki">`
> 
>     * `src="{{ "/assets/image.jpg" | url }}"` renders as `src="/assets/image.jpg"`
> 
> 
> I would expect each of these to start with `/folder` when they render (or `https://mysite.com/folder`), but none of them do.

Like you've figured out already, I believe all of these tags use the URL for the current site, rather than the `base_url` you've set in the SSG's config (that setting is only used for stuff inside the SSG itself).
