### ISSUE TITLE
base_url config doesn't use APP_URL env var unless using {{ permalink }}

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ssg#2]
Other tags like {{ mix }} should be able to take advantage of this too.

**Comment by jasonvarga** [comment]
I'm not really sure what this issue means. 😬 Feel free to reopen with more details.

**Comment by wesort** [comment]
I've just deployed from Statamic to Netlify for the first time yesterday and it's fantastic. Been using Netlify in other contexts for years, but this is my first time mixing my SALT stack with my JAM stack and it's fantastic.

I think I've just stumbled across what this issue _may_ have been referring to. Using `{{ permalink }}` in templating doesn't use the `APP_URL` (or `DEPLOY_URL`). 

### Templating 
`<link rel="canonical" href="{{ permalink }}"/>`

### Outputs for the page `/author`
`<link rel="canonical" href="https://6581e7880ee59d0008e5817c--ssg-andrea-levy.netlify.app/author"/>` 

---

### Deployment via Netlify
**`netlify.toml`**
```
[build]
publish = "storage/app/static"
command = "composer ssg"

[context.production.environment]
PHP_VERSION="8.1"
```

**`composer.json` > `scripts`**
```
"ssg": [
    "npm run build",
    "@php -r \"file_exists('.env') || copy('docs/ssg.env', '.env');\"",
    "@php please assets:generate-presets",
    "@php please ssg:generate"
]
```

**`ssg.env`:**
```
APP_URL="https://andrealevy.co.uk"
DEPLOY_URL="https://andrealevy.co.uk"
```

### Workaround
Use `<link rel="canonical" href="{{ config:app:app_url }}{{ url }}"/>`

### `{{ vite }}` tag 
**NB:** This is also outputting the Netlify "deploy permalink" but that doesn't have an impact on SEO or performance so perhaps not a problem.

### `php please support:details`
<details><summary>Show details</summary>

**Environment**
Application Name
Laravel Version: 9.52.16
PHP Version: 8.1.10
Composer Version: 2.6.6
Environment: production
Debug Mode: ENABLED
URL
Maintenance Mode: OFF

**Cache**
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

**Drivers**
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

**Statamic**
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.41.0 PRO

**Statamic Addons**
statamic/ssg: 2.2.0

</details>
