### ISSUE TITLE
Netlify: {{ locale }} is always default

### ISSUE THREAD

**Issue by robbinjohansson** [statamic/ssg#20]
Maybe not an issue with the actual ssg package, but the output of `{{ locale }}` is always the default one when deployed to netlify. Works fine locally.

```php
// config/statamic/sites.php

'sites' => [

    'default' => [
        'name' => 'default',
        'locale' => 'en',
        'url' => '/',
    ],
    'se' => [
        'name' => 'Sweden',
        'locale' => 'sv_SE',
        'url' => '/se/',
    ],
    'zh-cn' => [
        'name' => 'China',
        'locale' => 'zh_CN',
        'url' => '/zh-cn/',
    ],

]
```

`{{ locale }}` output:

```
https://myapp.netlify.app/ // 'default'
https://myapp.netlify.app/se // 'default'
https://myapp.netlify.app/zh-cn // 'default'
```

Maybe it's just not possible to use variables like this when statically generating the site?

**Comment by tao** [comment]
I also found that in my layout, the variables {{ site_name }} and {{ site_short_locale }} come out blank with SSG, perhaps it's related.

``` html
<!doctype html>
<html lang="{{ site_short_locale }}">
<head>
    <meta charset="utf-8">
    <title>{{ site_name }}</title>
</head>
```

**Comment by tao** [comment]
Using the variables this way seems to work fine:

```
{{ site:short_locale }}
{{ site:locale }}
{{ site:name }}
```

**Comment by jasonvarga** [comment]
Use the variables as described above.

**Comment by jasonvarga** [comment]
Actually this might be related to [this comment](https://github.com/statamic/ssg/issues/38#issuecomment-717129134). Investigating.

**Comment by jasonvarga** [comment]
Closing in favor of #43
