### ISSUE TITLE
Additional URLs doesn't handle query strings

### ISSUE THREAD

**Issue by tao** [statamic/ssg#22]
Related to issue #10 and pagination. I believe the additional URLs doesn't pass any query string variables and it's returning 404s.

```
    'urls' => [
        'foo',            // works
        'bar'             // works
        'bar?page=1',     // 404
    ],
```

I came across this when trying to generate the pagination partials statically, and I believe it's because it's requesting `bar?page=1` literally and that route doesn't exist.

```
[✔] /
[✔] /foo
[✔] /bar
[✘] /bar?page=1 (Resulted in 404)
```

The routes I used for testing in `web.php` are as follows:

```php
Route::get('/foo', function () { return 'foo'; });
Route::statamic('/bar', 'news._pagination', ['layout' => null]);
```

**Comment by jasonvarga** [comment]
I don't think you'll ever be able to generate a page with a query string. It doesn't translate to a file. There's a pagination workaround in #10
