### ISSUE TITLE
Install errors and "There are no commands defined in the "ssg" namespace"

### ISSUE THREAD

**Issue by DrTrills** [statamic/ssg#36]
`composer require statamic/ssg`

Using version ^0.2.0 for statamic/ssg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

`php please ssg:generate
`

`  There are no commands defined in the "ssg" namespace.`

On another site, I got the same but ran the ssg:generate command again and it ran with no problem

**Comment by damcclean** [comment]
It looks like Composer is running out of memory when trying to install the ssg package, which will be why the command can't be found.

I've written a [little short tutorial](https://duncanm.dev/bypass-composer-memory-issue) on how to get round that...

**Comment by DrTrills** [comment]
Thanks @damcclean

**Comment by intrepidws** [comment]
@duncanmcclean Any chance this post still exists somewhere? The link doesn't work.

**Comment by duncanmcclean** [comment]
> @duncanmcclean Any chance this post still exists somewhere? The link doesn't work.

It's no longer needed - update yo Composer 2 and it should work fine.

**Comment by intrepidws** [comment]
Hmm... it works fine locally but I'm getting the `There are no commands defined in the "ssg" namespace.` error when Netlify tries to build my site.

**Comment by intrepidws** [comment]
False alarm, I'm an idiot. It helps when you actually commit the addition of the SSG in the first place...
