### ISSUE TITLE
Multiple blueprints use using the same template with different fieds leak data

### ISSUE THREAD

**Issue by RussBrown00** [statamic/ssg#37]
If multiple blueprints use the same template but don't have all the same fields, it is possible for data from one collection to leak into another. 

The result of this for me was data from one page showing up on another.

The temp patch was to cross-add the missing types to the inverse pages and my problem was fixed

**Comment by tao** [comment]
So this might be related to this problem I was having on #15?

**Comment by padders** [comment]
I think we have this issue too, we have a topics page that shows 3 different kinds of posts that get completely messed up when run through the ssg.

**Comment by tao** [comment]
The same issue appears when using `yield` sections in the antlers layouts. If the `yield` is not used it generates the page with data from another collection item or page that did use this yield section.

**Comment by tao** [comment]
I've created an [example repo](https://github.com/tao/ssg-data-leak) to test this issue. If you open up the website normally it works fine:

![Screenshot 2020-12-30 at 22 41 45](https://user-images.githubusercontent.com/1446331/103380049-5bf01800-4af0-11eb-879c-cb02c1bc35ce.png)

![Screenshot 2020-12-30 at 22 43 37](https://user-images.githubusercontent.com/1446331/103380086-79bd7d00-4af0-11eb-8313-b074a0c2abbb.png)


Once you generate the static website you can see each page shows data is leaking in different ways. On Page Two, the header leaks through the `yield:header` in the layout.

![Screenshot 2020-12-30 at 22 41 49](https://user-images.githubusercontent.com/1446331/103380051-60b4cc00-4af0-11eb-8ad7-b053d94daa9f.png)

While the `test` and `404` pages have data leaking from the blueprint where a field called `extra` is defined but null on these pages.

![Screenshot 2020-12-30 at 22 41 52](https://user-images.githubusercontent.com/1446331/103380053-614d6280-4af0-11eb-92e0-175a67bd15bf.png)
![Screenshot 2020-12-30 at 22 41 55](https://user-images.githubusercontent.com/1446331/103380056-61e5f900-4af0-11eb-9ddb-42301a3203a3.png)

I have tried to debug and find a solution to this myself but I've had no luck yet. My best guess is that when SSG calls the Cascade, it fetches an instance. The Cascade uses `get` and `set` methods to store data but the older fields are not cleared when the entry or blueprint changes? As SSG runs in one process, the Cascade instance is not cleared between page renders, while if you fetch the page from the browser it creates a new instance of the Laravel app on each request?

**Comment by rustypaul** [comment]
Is there any update on whether this might be fixed soon? This is actively preventing us using Statamic currently when we desperately want to, especially now it has graphql coming.

**Comment by tao** [comment]
I had an email conversation with @jackmcdade in the beginning of January and he mentioned getting 3.1 shipped and these SSG issues were a high priority but I don't believe there's been any further updates on SSG since then. I'm sure it'll be looked at soon.
