### ISSUE TITLE
Statamic Multi-site not working correctly

### ISSUE THREAD

**Issue by tao** [statamic/ssg#43]
I've created a simple [example repository](https://github.com/tao/ssg-multisite) with Statamic Multi-site for two languages to demonstrate some problems using SSG.

![Screenshot 2021-01-01 at 12 30 30](https://user-images.githubusercontent.com/1446331/103437203-374d8a80-4c2d-11eb-9923-e71e18bc2f00.png)
![Screenshot 2021-01-01 at 12 53 08](https://user-images.githubusercontent.com/1446331/103437426-51d53300-4c30-11eb-8040-8d450b1081d6.png)

Some things that work on Statamic but are currently not working correctly on the static site:

- [ ] The Italian homepage doesn't update the navbar active state (where "current_uri" == "url")
- [ ] The nav doesn't know which site it's on (urls don't update: "/news" vs "/it/news")
- [ ] The background colour doesn't change based on `{{ site:handle }}`
- [ ] Locales tag logic on the "news/show" layout doesn't work with `locale:handle == site:handle` on both sites
- [ ] The Italian "/it/news" page doesn't show Italian news articles
- [ ] Related news on Italian News article doesn't show Italian news articles
- [ ] The trans tag `{{ trans:news.related }}` doesn't work on "news/show" layout
- [ ] The trans tag on the homepage doesn't work either `{{ trans:news.welcome }}`
- [ ] *News articles produce `page__news--dinosaur-angels` from url segments (in body class), but break on static site for different languages: `page__it--news`

**Comment by mvolpato** [comment]
Hi @tao, can you have a look if [this](https://github.com/statamic/ssg/issues/38#issuecomment-717129134) also happens in your example? I do not think you are using `segments` now. You could add it to the list so that everything is in one place.

**Comment by tao** [comment]
@mvolpato I've updated the list with the issue related to languages pages, which does seem to be incorrect where `segment_1` is equal to `it` instead of `news`. That does seem like a multi-site related issue...

However, I believe the other issues [mentioned](#38) are more related to the [leaking data issue](https://github.com/statamic/ssg/issues/37#issuecomment-752754673) and I've created another example project related to that specifically.
