### ISSUE TITLE
Slow when using Reponsive Images addon

### ISSUE THREAD

**Issue by jasonvarga** [statamic/ssg#56]
Related to #55

The [responsive images](https://github.com/spatie/statamic-responsive-images) seems to generate more variants than I would have expected. Need to work out _why_, and really understand the rationale behind which variants should be generated and make the ssg use those somehow.

The addon has to do with browser size. Since there's no browser, we might need to fake something.

(@riasvdv - You don't have to spend any time on this, but if any of this sounds familiar to you, a tip in the right direction would be helpful)

**Comment by riasvdv** [comment]
The addon doesn't use browser size to determine the variants, it uses a fairly straightforward "WidthCalculator" that determines the ideal px/kb ratios for generating images and lets the browser pick the best one based on how wide the image is displayed.

https://github.com/spatie/statamic-responsive-images/blob/master/src/WidthCalculator.php

It is a big performance hit though, and on my sites I don't enable asset caching, so they're only generated when they're actually requested (through the Glide url)

**Comment by lokmanm** [comment]
I just stumbled upon this, for a site with 10 pages and a lot of images it took 5 minutes to build the website.

Does glide has the same issue or not ? Thanks.

**Comment by BobWez98** [comment]
Any updates on this? I have seen a complete server go down when resizing images, any way to improve this?
