### ISSUE TITLE
Replace Statamic static cache with SSG files.

### ISSUE THREAD

**Issue by sarunaslite** [statamic/ssg#67]
The problem is with high traffic to our website, When Statamic regenerating new static files we get errors with the leaked data on the website. Maybe there is some way to replace it with SSG files?

**Comment by jasonvarga** [comment]
Can you explain this further? I don't really understand.

**Comment by sarunaslite** [comment]
Our production websites are in full cache strategy and in our website deploy flow we clean stache, cache, static update search, and in this process if we have a lot of customers in our website Statamic show errors with sensitive website data. It is hard to explain but with lower traffic, we do not have similar problems.
So it will be nice to generate static pages before deployment.
P.S. we clean static cache because sometimes some pages don’t refresh.

**Comment by jasonvarga** [comment]
You have the site _and_ the ssg on production?

**Comment by jasonvarga** [comment]
(This repo is for the static site generator, not the static caching feature. Perhaps you mean to open an issue on statamic/cms)

**Comment by sarunaslite** [comment]
Thank you
