### ISSUE TITLE
Multisite Manual Route Errors

### ISSUE THREAD

**Issue by adnweedon** [statamic/ssg#68]
I'm having trouble with generating the SSG for a multisite website, with errors for some pages like this:

![image](https://user-images.githubusercontent.com/81413869/130035522-21b3038b-7559-4257-a02a-46a28bd6341c.png)

My setup is that I have pages that are paginated (just on one of the sites), so in order to make that work statically, I followed the gist to set it up as /blog/page/3 etc, and so have manual routes for those links. Running on PHP8 with multiple workers.

What I think the problem is, is that when the SSG generates, in makeContentGenerationClosures() it loops through the pages and updates the current site - those manual routes are in the pages array, but for some reason the ->site() method on the Statamic\StaticSite\Route returns null, and then subsequently returns an error. 

For my scenario, I got it running without errors like this:

![image](https://user-images.githubusercontent.com/81413869/130036686-f6d5526a-0cb0-4ab3-b4f7-25e42c407d5a.png)

by defaulting back if null, but I have no idea if I have understood the problem correctly, and I'm having other issues with content leaking between sites, so I'm not confident enough to raise a PR!

**Comment by jasonvarga** [comment]
Just ran into this too.

The error happens when the base_url setting is different from what's defined in config/statamic/sites.php
