### ISSUE TITLE
Call to member raw() on string

### ISSUE THREAD

**Issue by devonbeard** [statamic/ssg#78]
Hey folks, 

When I try to run ```php please ssg:generate``` I'm getting these errors and not sure what is causing them. Do you have any insight or pointers? 

[✘] /blog/what-is-the-uniform-trust-code-what-is-the-uniform-probate-code (Call to a member function raw() on string)
[✘] /blog/sandwich-smarter-trustworthy (Call to a member function raw() on string)
[✘] /blog/is-trust-and-estate-planning-right-for-me (Call to a member function raw() on string)
[✘] /blog/what-is-your-domicile-and-why-it-matters (Call to a member function raw() on string)
[✘] /blog/is-it-safe-to-save-personal-and-family-documents-in-the-cloud (Call to a member function raw() on string)

**Comment by jasonvarga** [comment]
Do you get those errors when visiting them in the regular non-SSG site?
