### ISSUE TITLE
Suggest publishing the config after installing

### ISSUE THREAD

**Issue by jackmcdade** [statamic/ssg#85]

**Comment by jasonvarga** [comment]
I don't think many packages really suggest doing that.
The docs already mention to do it, and give you a copy/pasteable command.

Not enough?

**Comment by jackmcdade** [comment]
I've definitely seen it before, and given that the defaults probably won't work for anyone's site right out of the box, it seems like a good idea to me. I can remember to type `composer require statamic/ssg` without the docs, but I can't remember the syntax for vendor publish without pulling up the docs.

**Comment by jasonvarga** [comment]
Okay. 👍 

PS. You can just run `artisan vendor:publish` which is easy to remember, and you can just pick from the list so you don't have to remember the specific arguments.

**Comment by jackmcdade** [comment]
TIL <3
